In [2]:
#import libraries
import pandas as pd

In [10]:
#import dataset
df=pd.read_csv('../data/raw/train.csv')
df

,policy_id,policy_tenure,age_of_car,age_of_policyholder,area_cluster,population_density,make,segment,model,fuel_type,...,is_brake_assist,is_power_door_locks,is_central_locking,is_power_steering,is_driver_seat_height_adjustable,is_day_night_rear_view_mirror,is_ecw,is_speed_alert,ncap_rating,is_claim
0,ID00001,0.515874,0.05,0.644231,C1,4990,1,A,M1,CNG,...,No,No,No,Yes,No,No,No,Yes,0,0
1,ID00002,0.672619,0.02,0.375000,C2,27003,1,A,M1,CNG,...,No,No,No,Yes,No,No,No,Yes,0,0
2,ID00003,0.841110,0.02,0.384615,C3,4076,1,A,M1,CNG,...,No,No,No,Yes,No,No,No,Yes,0,0
3,ID00004,0.900277,0.11,0.432692,C4,21622,1,C1,M2,Petrol,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,2,0
4,ID00005,0.596403,0.11,0.634615,C5,34738,2,A,M3,Petrol,...,No,Yes,Yes,Yes,No,Yes,Yes,Yes,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58587,ID58588,0.355089,0.13,0.644231,C8,8794,2,A,M3,Petrol,...,No,Yes,Yes,Yes,No,Yes,Yes,Yes,2,0
58588,ID58589,1.199642,0.02,0.519231,C14,7788,1,A,M1,CNG,...,No,No,No,Yes,No,No,No,Yes,0,0
58589,ID58590,1.162273,0.05,0.451923,C5,34738,1,A,M1,CNG,...,No,No,No,Yes,No,No,No,Yes,0,0
58590,ID58591,1.236307,0.14,0.557692,C8,8794,1,B2,M6,Petrol,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,2,0
58591,ID58592,0.124429,0.02,0.442308,C8,8794,3,C2,M4,Diesel,...,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,3,0

# Underatnd Data Structure

In [11]:
#check shape of data_no of cols and rows
df.shape

(58592, 44)

In [12]:
#check columns
df.columns

Index(['policy_id', 'policy_tenure', 'age_of_car', 'age_of_policyholder',
       'area_cluster', 'population_density', 'make', 'segment', 'model',
       'fuel_type', 'max_torque', 'max_power', 'engine_type', 'airbags',
       'is_esc', 'is_adjustable_steering', 'is_tpms', 'is_parking_sensors',
       'is_parking_camera', 'rear_brakes_type', 'displacement', 'cylinder',
       'transmission_type', 'gear_box', 'steering_type', 'turning_radius',
       'length', 'width', 'height', 'gross_weight', 'is_front_fog_lights',
       'is_rear_window_wiper', 'is_rear_window_washer',
       'is_rear_window_defogger', 'is_brake_assist', 'is_power_door_locks',
       'is_central_locking', 'is_power_steering',
       'is_driver_seat_height_adjustable', 'is_day_night_rear_view_mirror',
       'is_ecw', 'is_speed_alert', 'ncap_rating', 'is_claim'],
      dtype='str')

In [19]:
#look into tha data
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
df.head()

,policy_id,policy_tenure,age_of_car,age_of_policyholder,area_cluster,population_density,make,segment,model,fuel_type,max_torque,max_power,engine_type,airbags,is_esc,is_adjustable_steering,is_tpms,is_parking_sensors,is_parking_camera,rear_brakes_type,displacement,cylinder,transmission_type,gear_box,steering_type,turning_radius,length,width,height,gross_weight,is_front_fog_lights,is_rear_window_wiper,is_rear_window_washer,is_rear_window_defogger,is_brake_assist,is_power_door_locks,is_central_locking,is_power_steering,is_driver_seat_height_adjustable,is_day_night_rear_view_mirror,is_ecw,is_speed_alert,ncap_rating,is_claim
0,ID00001,0.515874,0.05,0.644231,C1,4990,1,A,M1,CNG,60Nm@3500rpm,40.36bhp@6000rpm,F8D Petrol Engine,2,No,No,No,Yes,No,Drum,796,3,Manual,5,Power,4.6,3445,1515,1475,1185,No,No,No,No,No,No,No,Yes,No,No,No,Yes,0,0
1,ID00002,0.672619,0.02,0.375000,C2,27003,1,A,M1,CNG,60Nm@3500rpm,40.36bhp@6000rpm,F8D Petrol Engine,2,No,No,No,Yes,No,Drum,796,3,Manual,5,Power,4.6,3445,1515,1475,1185,No,No,No,No,No,No,No,Yes,No,No,No,Yes,0,0
2,ID00003,0.841110,0.02,0.384615,C3,4076,1,A,M1,CNG,60Nm@3500rpm,40.36bhp@6000rpm,F8D Petrol Engine,2,No,No,No,Yes,No,Drum,796,3,Manual,5,Power,4.6,3445,1515,1475,1185,No,No,No,No,No,No,No,Yes,No,No,No,Yes,0,0
3,ID00004,0.900277,0.11,0.432692,C4,21622,1,C1,M2,Petrol,113Nm@4400rpm,88.50bhp@6000rpm,1.2 L K12N Dualjet,2,Yes,Yes,No,Yes,Yes,Drum,1197,4,Automatic,5,Electric,4.8,3995,1735,1515,1335,Yes,No,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,2,0
4,ID00005,0.596403,0.11,0.634615,C5,34738,2,A,M3,Petrol,91Nm@4250rpm,67.06bhp@5500rpm,1.0 SCe,2,No,No,No,No,Yes,Drum,999,3,Automatic,5,Electric,5.0,3731,1579,1490,1155,No,No,No,No,No,Yes,Yes,Yes,No,Yes,Yes,Yes,2,0

In [14]:
#dataframe structure and missing data summary
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 58592 entries, 0 to 58591
Data columns (total 44 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   policy_id                         58592 non-null  str
 1   policy_tenure                     58592 non-null  float64
 2   age_of_car                        58592 non-null  float64
 3   age_of_policyholder               58592 non-null  float64
 4   area_cluster                      58592 non-null  str
 5   population_density                58592 non-null  int64
 6   make                              58592 non-null  int64
 7   segment                           58592 non-null  str
 8   model                             58592 non-null  str
 9   fuel_type                         58592 non-null  str
 10  max_torque                        58592 non-null  str
 11  max_power                         58592 non-null  str
 12  engine_type                       58592 non-null  str
 13  airbags                           58592 non-null  int64
 14  is_esc                            58592 non-null  str
 15  is_adjustable_steering            58592 non-null  str
 16  is_tpms                           58592 non-null  str
 17  is_parking_sensors                58592 non-null  str
 18  is_parking_camera                 58592 non-null  str
 19  rear_brakes_type                  58592 non-null  str
 20  displacement                      58592 non-null  int64
 21  cylinder                          58592 non-null  int64
 22  transmission_type                 58592 non-null  str
 23  gear_box                          58592 non-null  int64
 24  steering_type                     58592 non-null  str
 25  turning_radius                    58592 non-null  float64
 26  length                            58592 non-null  int64
 27  width                             58592 non-null  int64
 28  height                            58592 non-null  int64
 29  gross_weight                      58592 non-null  int64
 30  is_front_fog_lights               58592 non-null  str
 31  is_rear_window_wiper              58592 non-null  str
 32  is_rear_window_washer             58592 non-null  str
 33  is_rear_window_defogger           58592 non-null  str
 34  is_brake_assist                   58592 non-null  str
 35  is_power_door_locks               58592 non-null  str
 36  is_central_locking                58592 non-null  str
 37  is_power_steering                 58592 non-null  str
 38  is_driver_seat_height_adjustable  58592 non-null  str
 39  is_day_night_rear_view_mirror     58592 non-null  str
 40  is_ecw                            58592 non-null  str
 41  is_speed_alert                    58592 non-null  str
 42  ncap_rating                       58592 non-null  int64
 43  is_claim                          58592 non-null  int64
dtypes: float64(4), int64(12), str(28)
memory usage: 19.7 MB

# Identify features types
  ##The dataset contains:
- Numerical features: measurable numerical values
- Categorical features: categories or codes representing groups
- Binary features: features with two possible states
- Structured string features: text containing useful information that may require extraction
- Identifier: uniquely identifies each record
- Target: the variable we want to predic

In [37]:
# Numerical features
numerical_features = [
    "policy_tenure",
    "age_of_car",
    "age_of_policyholder",
    "population_density",
    "airbags",
    "displacement",
    "cylinder",
    "turning_radius",
    "length",
    "width",
    "height",
    "gross_weight"
]

# Categorical features
categorical_features = [
    "area_cluster",
    "make",
    "segment",
    "model",
    "fuel_type",
    "engine_type",
    "rear_brakes_type",
    "transmission_type",
    "steering_type",
    "gear_box",
    "ncap_rating"
]

# Binary features
binary_features = [
    "is_esc",
    "is_adjustable_steering",
    "is_tpms",
    "is_parking_sensors",
    "is_parking_camera",
    "is_front_fog_lights",
    "is_rear_window_wiper",
    "is_rear_window_washer",
    "is_rear_window_defogger",
    "is_brake_assist",
    "is_power_door_locks",
    "is_central_locking",
    "is_power_steering",
    "is_driver_seat_height_adjustable",
    "is_day_night_rear_view_mirror",
    "is_ecw",
    "is_speed_alert"
]

# Structured string features
structured_string_features = [
    "max_torque",
    "max_power"
]

# Identifier
identifier = ["policy_id"]

# Target
target = ["is_claim"]

### Observations

Feature types were identified based on the meaning of the variables, not only their Pandas data types.

- `make` has an `int64` data type, but its values (1–5) represent different vehicle manufacturers/makes. Therefore, it is treated as a categorical feature rather than a numerical feature.
- `gear_box` has an `int64` data type, with values 5 and 6. These represent gearbox categories, so it is treated as a categorical feature.
- `policy_id` is an identifier and does not represent a meaningful predictive feature.
- `is_claim` is the target variable, representing whether an insurance claim was made.
- `max_torque` and `max_power` are structured string features because they contain numerical information within text.

# Data Quality

In [ ]:
#check missing values
df.isnull().sum()

policy_id                           0
policy_tenure                       0
age_of_car                          0
age_of_policyholder                 0
area_cluster                        0
population_density                  0
make                                0
segment                             0
model                               0
fuel_type                           0
max_torque                          0
max_power                           0
engine_type                         0
airbags                             0
is_esc                              0
is_adjustable_steering              0
is_tpms                             0
is_parking_sensors                  0
is_parking_camera                   0
rear_brakes_type                    0
displacement                        0
cylinder                            0
transmission_type                   0
gear_box                            0
steering_type                       0
turning_radius                      0
length                              0
width                               0
height                              0
gross_weight                        0
is_front_fog_lights                 0
is_rear_window_wiper                0
is_rear_window_washer               0
is_rear_window_defogger             0
is_brake_assist                     0
is_power_door_locks                 0
is_central_locking                  0
is_power_steering                   0
is_driver_seat_height_adjustable    0
is_day_night_rear_view_mirror       0
is_ecw                              0
is_speed_alert                      0
ncap_rating                         0
is_claim                            0
dtype: int64

In [ ]:
#duplicate rows
df.duplicated().sum()

np.int64(0)

In [40]:
# unique values in categorical features
df[categorical_features].nunique()

area_cluster         22
make                  5
segment               6
model                11
fuel_type             3
engine_type          11
rear_brakes_type      2
transmission_type     2
steering_type         3
gear_box              2
ncap_rating           5
dtype: int64

In [39]:
# constant features in numerical features
df[numerical_features].nunique()

policy_tenure          58592
age_of_car                49
age_of_policyholder       75
population_density        22
airbags                    3
displacement               9
cylinder                   2
turning_radius             9
length                     9
width                     10
height                    11
gross_weight              10
dtype: int64

In [42]:
# check invalid values for numerical features
df[numerical_features].describe().T[['max','min']]

                              max          min
policy_tenure            1.396641     0.002735
age_of_car               1.000000     0.000000
age_of_policyholder      1.000000     0.288462
population_density   73430.000000   290.000000
airbags                  6.000000     1.000000
displacement          1498.000000   796.000000
cylinder                 4.000000     3.000000
turning_radius           5.200000     4.500000
length                4300.000000  3445.000000
width                 1811.000000  1475.000000
height                1825.000000  1475.000000
gross_weight          1720.000000  1051.000000

In [45]:
# check invalid values for categorical features
for col in categorical_features:
    print(col , df[col].unique())

area_cluster <StringArray>
[ 'C1',  'C2',  'C3',  'C4',  'C5',  'C6',  'C7',  'C8',  'C9', 'C10', 'C11',
 'C12', 'C13', 'C14', 'C15', 'C16', 'C17', 'C18', 'C19', 'C20', 'C21', 'C22']
Length: 22, dtype: str
make [1 2 3 4 5]
segment <StringArray>
['A', 'C1', 'C2', 'B2', 'B1', 'Utility']
Length: 6, dtype: str
model <StringArray>
['M1', 'M2', 'M3', 'M4', 'M5', 'M6', 'M7', 'M8', 'M9', 'M10', 'M11']
Length: 11, dtype: str
fuel_type <StringArray>
['CNG', 'Petrol', 'Diesel']
Length: 3, dtype: str
engine_type <StringArray>
[        'F8D Petrol Engine',        '1.2 L K12N Dualjet',
                   '1.0 SCe',             '1.5 L U2 CRDi',
 '1.5 Turbocharged Revotorq',         'K Series Dual jet',
     '1.2 L K Series Engine',                      'K10C',
                    'i-DTEC',                      'G12B',
 '1.5 Turbocharged Revotron']
Length: 11, dtype: str
rear_brakes_type <StringArray>
['Drum', 'Disc']
Length: 2, dtype: str
transmission_type <StringArray>
['Manual', 'Automatic']
Length: 2, dtype: str
steering_type <StringArray>
['Power', 'Electric', 'Manual']
Length: 3, dtype: str
gear_box [5 6]
ncap_rating [0 2 3 5 4]

In [46]:
# check invalid values for binary features
for col in binary_features:
    print(col , df[col].unique())

is_esc <StringArray>
['No', 'Yes']
Length: 2, dtype: str
is_adjustable_steering <StringArray>
['No', 'Yes']
Length: 2, dtype: str
is_tpms <StringArray>
['No', 'Yes']
Length: 2, dtype: str
is_parking_sensors <StringArray>
['Yes', 'No']
Length: 2, dtype: str
is_parking_camera <StringArray>
['No', 'Yes']
Length: 2, dtype: str
is_front_fog_lights <StringArray>
['No', 'Yes']
Length: 2, dtype: str
is_rear_window_wiper <StringArray>
['No', 'Yes']
Length: 2, dtype: str
is_rear_window_washer <StringArray>
['No', 'Yes']
Length: 2, dtype: str
is_rear_window_defogger <StringArray>
['No', 'Yes']
Length: 2, dtype: str
is_brake_assist <StringArray>
['No', 'Yes']
Length: 2, dtype: str
is_power_door_locks <StringArray>
['No', 'Yes']
Length: 2, dtype: str
is_central_locking <StringArray>
['No', 'Yes']
Length: 2, dtype: str
is_power_steering <StringArray>
['Yes', 'No']
Length: 2, dtype: str
is_driver_seat_height_adjustable <StringArray>
['No', 'Yes']
Length: 2, dtype: str
is_day_night_rear_view_mirror <StringArray>
['No', 'Yes']
Length: 2, dtype: str
is_ecw <StringArray>
['No', 'Yes']
Length: 2, dtype: str
is_speed_alert <StringArray>
['Yes', 'No']
Length: 2, dtype: str

# Identify structural issues
 
The dataset was checked for structural inconsistencies.

- Categorical and binary features were inspected for inconsistent text representations. No obvious inconsistencies were found.
- `make` and `gear_box` are stored as integers but represent categorical information. Their meaning was identified during feature-type classification.
- `max_torque` and `max_power` are structured string features containing numerical information. They may require feature extraction later during feature engineering/preprocessing.
- No immediate structural corrections are required at this stage.

In [49]:

df[categorical_features].apply(lambda col: col.astype(str).str.strip().nunique())

area_cluster         22
make                  5
segment               6
model                11
fuel_type             3
engine_type          11
rear_brakes_type      2
transmission_type     2
steering_type         3
gear_box              2
ncap_rating           5
dtype: int64

In [50]:
df[binary_features].apply(lambda col: col.astype(str).str.strip().nunique())

is_esc                              2
is_adjustable_steering              2
is_tpms                             2
is_parking_sensors                  2
is_parking_camera                   2
is_front_fog_lights                 2
is_rear_window_wiper                2
is_rear_window_washer               2
is_rear_window_defogger             2
is_brake_assist                     2
is_power_door_locks                 2
is_central_locking                  2
is_power_steering                   2
is_driver_seat_height_adjustable    2
is_day_night_rear_view_mirror       2
is_ecw                              2
is_speed_alert                      2
dtype: int64

# Observation 
 - Categorical and binary features were inspected for inconsistent text representations. No obvious inconsistencies were found.
- `make` and `gear_box` are stored as integers but represent categorical information. Their meaning was identified during feature-type classification.
- `max_torque` and `max_power` are structured string features containing numerical information. They may require feature extraction later during feature engineering/preprocessing.
- No immediate structural corrections are required at this stage.

# Remove irrelevant /identifier columns

In [51]:

df = df.drop(columns=["policy_id"])

In [52]:
df.shape

(58592, 43)

# Seperate target and features col

In [53]:
X=df.drop(columns=['is_claim'])
Y=df['is_claim']

In [57]:
X.shape

(58592, 42)

In [58]:
Y.shape

(58592,)

# Sanity check

In [60]:
Y.value_counts()

is_claim
0    54844
1     3748
Name: count, dtype: int64

In [61]:
"is_claim" in X.columns

False

In [62]:
"policy_id" in X.columns

False

# save data

In [63]:
df.to_csv("../data/processed/train_prepared.csv", index=False)